name: Java-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Download latest snapshot
        run: mvn dependency:resolve
      - name: Build with Ant
        run: ant release
      - name: Publish coverage
        run: bash <(curl -s https://codecov.io/bash) -f target/reports/coverage/all/coverage.xml